# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Poor man's ngrok"
  homepage "https://github.com/pgrok/pgrok"
  version "2026.01.08-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgrok/pgrok/releases/download/v2026.01.08-1/pgrok_2026.01.08-1_darwin_amd64.tar.gz"
      sha256 "63c869b7b27948f7875297e09a16ecf8167e6706385bb83e36936473ab65faf1"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgrok/pgrok/releases/download/v2026.01.08-1/pgrok_2026.01.08-1_darwin_arm64.tar.gz"
      sha256 "5d9af8f0612c5307a2752616f56b85e6d95f8a7ff7b767b79795132857cf6d31"

      def install
        bin.install "pgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrok/pgrok/releases/download/v2026.01.08-1/pgrok_2026.01.08-1_linux_amd64.tar.gz"
      sha256 "c4b3a5d99f92076d4bd1f412612a36f333c9b9a62056e82be26fa4ab5c8faf13"
      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrok/pgrok/releases/download/v2026.01.08-1/pgrok_2026.01.08-1_linux_arm64.tar.gz"
      sha256 "15eabdc65d0f128ff940118f15be4e2d85d532927018f9785d9b02c415b9f32a"
      def install
        bin.install "pgrok"
      end
    end
  end
end
