# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Poor man's ngrok"
  homepage "https://github.com/pgrok/pgrok"
  version "1.4.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pgrok/pgrok/releases/download/v1.4.0-rc.1/pgrok_1.4.0-rc.1_darwin_arm64.tar.gz"
      sha256 "ba1ca030121dca90306a603562933e16b466e536674c2cea1f2f58c7b1cc7552"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pgrok/pgrok/releases/download/v1.4.0-rc.1/pgrok_1.4.0-rc.1_darwin_amd64.tar.gz"
      sha256 "62531cedc08d362291e4cdd5a19b2de3038666c2be7d6c4be329f9848616fa19"

      def install
        bin.install "pgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pgrok/pgrok/releases/download/v1.4.0-rc.1/pgrok_1.4.0-rc.1_linux_amd64.tar.gz"
      sha256 "e1435d58337dff4c73e41b6aab7890bd4dc0228fc0487b8f04f2581bf933061b"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrok/pgrok/releases/download/v1.4.0-rc.1/pgrok_1.4.0-rc.1_linux_arm64.tar.gz"
      sha256 "ae46f606e680b8b96725a8a4f9d29b25e2d8f9c8b4f5d14dbcb39de42fb021a1"

      def install
        bin.install "pgrok"
      end
    end
  end
end
