# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Poor man's ngrok"
  homepage "https://github.com/pgrok/pgrok"
  version "2025.10.29-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgrok/pgrok/releases/download/v2025.10.29-1/pgrok_2025.10.29-1_darwin_amd64.tar.gz"
      sha256 "d4379893841d9461b811a267b7f488c9c8668c48e6a49345f161ce52fe2be2b7"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgrok/pgrok/releases/download/v2025.10.29-1/pgrok_2025.10.29-1_darwin_arm64.tar.gz"
      sha256 "332d9cbf2bbca7c7c587b11d99af896186208bcb8afc8e7666fda0b172135439"

      def install
        bin.install "pgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrok/pgrok/releases/download/v2025.10.29-1/pgrok_2025.10.29-1_linux_amd64.tar.gz"
      sha256 "13e5e02482b51d4556dd41b718ef6e966ea54158d300615071fd2416e5346f19"
      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrok/pgrok/releases/download/v2025.10.29-1/pgrok_2025.10.29-1_linux_arm64.tar.gz"
      sha256 "aedc0efc4ba06adb305270a40217783df47468903fb3b3fd986e03c2aeef6a64"
      def install
        bin.install "pgrok"
      end
    end
  end
end
